export enum CharacterGender {
	Male = 1,
	Female = 2,
}

export enum InventoryType {
	INVENTORY = 2,
	EQUIPPED = 3,
	STASH_1 = 4,
	STASH_2 = 5,
	STASH_3 = 6,
	STASH_4 = 7,
	STASH_5 = 8,
	STASH_6 = 9,
	SHARED_STASH = 20,
}

export {
	Define_Account_CurrencyType as ECurrencyType,
	Define_Account_LoginType as ELoginType,
	Define_Account_AccountStatus as EAccountStatus,
	Define_Item_InventoryId as EInventoryId,
	Define_Item_rarityType as ERarityType,
	Define_Item_LootState as ELootState,
	Define_Equipment_SlotId as ESlotId,
	Define_Message_LoopFlag as ELoopFlag,
	Define_Message_UpdateFlag as EUpdateFlag,
	Define_Message_SelectFlag as ESelectFlag,
	Define_Match_Match_Region as EMatchRegion,
	Define_Stat_StatType as EStatType,
	Define_Game_AdvPointType as EAdvPointType,
	Define_Game_GameType as EGameType,
	Define_Game_Floor as EGameFloor,
	Define_Common_MetaLocation as EMetaLocation,
	Define_Common_ServerLocation as EServerLocation,
	Define_Class_Type as EClassType,
	Define_Class_Move as EMoveType,
	Define_Chat_Type as EChatType,
	Define_Chat_RoomType as EChatRoomType,
	Define_Trade_Requirement_Type as ETradeRequirement,
	Operate_Policy as EPolicy,
	Define_Hack_Policy as EHackPolicy,
	Define_Hack_banType as EBanType,
	Define_Report_Category as EReportCategory,
	Define_Karma_Action as EKarmaAction,
	Define_Karma_Status as EKarmaStatus,
	Define_Coupon_Type as ECouponType,
	Define_Shop_Type as EShopType,
	Define_Shop_PaymentMethod as EPaymentMethod,
	Define_Shop_SalesChannelType as ESalesChannelType,
	Define_Reward_RewardType as ERewardType,
	CharacterGenderType as ECharacterGender,
	PacketResult as EPacketResult,
	SS2C_ACCOUNT_LOGIN_RES_RESULT as EAccountLoginResult,
	SC2S_AUTO_MATCH_REG_REQ_MODE as EAutoMatchRegisterMode,
	SS2C_AUTO_MATCH_REG_RES_RESULT as EAutoMatchRegisterResult,
	SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO as EInventoryInfoResult,
	SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE as EInventoryAllUpdateResult,
	SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE as EInventorySingleUpdateResult,
	SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO as EStorageInfoResult,
	IronMace_Login_Res_IronMace_Login_Result as EIronMaceLoginResult,
	MARKETPLACE_FILTER as EMarketplaceFilter,
	MARKETPLACE_SORT as EMarketplaceSort,
	MARKETPLACE_MY_ITEM_STATE as EMarketplaceItemState,
	SMERCHANT_INFO_FLAG as EMerchantInfoFlag,
	SMERCHANT_QUEST_INFO_FLAG as EQuestInfoFlag,
	SS2C_MERCHANT_RECOVERY_ITEM_CHECK_NOT_FLAG as ERecoverItemCheckFlag,
	PARTY_INVITE_ANSWER as EPartyInviteAnswer,
	SRANKING_REWARD_INFO_REWARD_STATE as ERankingRewardState,
	SRANKING_INFO_STATE as ERankingInfoState,
	RANKING_TYPE as ERankingType,
	CONTENT_TYPE as EContentType,
} from "@dad-js/dad-api/pb";
